[E 2024-03-23 17:03:32,860 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 500}, 'response': {'detail': 'Internal Server Error'}}
[E 2024-03-23 17:04:06,425 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 500}, 'response': {'detail': 'Internal Server Error'}}
[E 2024-03-23 17:05:47,154 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': "Token doesn't have production permission.", 'ip_address': '118.150.47.40', 'person_id': 'F129970274', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2024-03-23 17:06:07,896 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': "Token doesn't have production permission.", 'ip_address': '118.150.47.40', 'person_id': 'F129970274', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2024-03-23 17:10:20,719 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': "Token doesn't have production permission.", 'ip_address': '118.150.47.40', 'person_id': 'F129970274', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2024-03-24 17:31:01,902 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 422}, 'response': {'detail': [{'loc': ['body', 'scanner_input', 'date'], 'msg': 'invalid date format', 'type': 'value_error.date'}]}}
[E 2024-04-14 15:37:43,432 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 422}, 'response': {'detail': [{'loc': ['body', 'kbar_input', 'end'], 'msg': 'invalid date format', 'type': 'value_error.date'}]}}
[E 2024-04-14 15:38:02,398 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 422}, 'response': {'detail': [{'loc': ['body', 'kbar_input', 'end'], 'msg': 'invalid date format', 'type': 'value_error.date'}]}}
[E 2024-04-14 15:38:15,638 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 422}, 'response': {'detail': [{'loc': ['body', 'kbar_input', 'end'], 'msg': 'invalid date format', 'type': 'value_error.date'}]}}
[E 2024-04-14 15:38:33,813 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 422}, 'response': {'detail': [{'loc': ['body', 'kbar_input', 'end'], 'msg': 'invalid date format', 'type': 'value_error.date'}]}}
[E 2024-04-14 15:44:00,981 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 422}, 'response': {'detail': [{'loc': ['body', 'kbar_input', 'end'], 'msg': 'invalid date format', 'type': 'value_error.date'}]}}
[E 2024-04-14 16:19:36,236 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/shioaji.py:231:_setup_solace] RequestException RemoteDisconnected('Remote end closed connection without response')
[E 2024-04-14 20:26:52,118 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '118.150.47.40', 'person_id': 'F129970274', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2024-04-14 20:29:58,951 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '118.150.47.40', 'person_id': 'F129970274', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2024-04-14 20:34:40,846 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '118.150.47.40', 'person_id': 'F129970274', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2024-04-14 20:35:11,751 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '118.150.47.40', 'person_id': 'F129970274', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
